/**
 * STEP 0.2 - parity tests.
 *
 * Each test compares what the new equipment rules produce against the legacy
 * fixtures in tests/fixtures/parity/ (generated by scripts/build-parity-fixtures.ts).
 * These are expected to fail until STEP 1-4 land; the failure messages report the
 * item counts that are extra or missing so the gap stays legible while it closes.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import type {
  CatalogManifest,
  CatalogSearchItem,
} from "../src/lib/catalog/types";
import {
  itemMatchesClass,
  legacyClassToken,
} from "../src/lib/equipment/class-compatibility";
import { resolveWeaponCapabilities } from "../src/lib/equipment/catalog-rules";
import type { EquipmentSlot } from "../src/lib/equipment/types";

const projectRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

function readJson<T>(relativePath: string): T {
  return JSON.parse(
    readFileSync(path.resolve(projectRoot, relativePath), "utf8"),
  ) as T;
}

function fixture<T>(name: string): T {
  return readJson<T>(path.join("tests", "fixtures", "parity", name));
}

const manifest = readJson<CatalogManifest>("public/data/catalog-manifest.json");
const catalog = readJson<CatalogSearchItem[]>(
  path.join("public", manifest.search.url.replace(/^\//, "")),
);
const catalogById = new Map(catalog.map((item) => [item.id, item]));

/** Reports the symmetric difference rather than just "not equal". */
function assertSameIds(actual: number[], expected: number[], label: string) {
  const actualSet = new Set(actual);
  const expectedSet = new Set(expected);
  const extra = actual.filter((id) => !expectedSet.has(id));
  const missing = expected.filter((id) => !actualSet.has(id));

  const describe = (ids: number[]) =>
    ids
      .slice(0, 8)
      .map((id) => `${id} ${catalogById.get(id)?.name ?? "?"}`)
      .join(", ");

  assert.deepEqual(
    { extra: extra.length, missing: missing.length },
    { extra: 0, missing: 0 },
    `${label}: expected ${expected.length} items, got ${actual.length}.` +
      `\n  extra (${extra.length}): ${describe(extra)}` +
      `\n  missing (${missing.length}): ${describe(missing)}`,
  );
}

/** Reads the shipped catalog rather than recomputing, so the built asset is what is under test. */
function catalogIdsForSlot(slot: EquipmentSlot): number[] {
  return catalog
    .filter((item) => item.equipSlots.includes(slot))
    .map((item) => item.id);
}

test("left weapon list matches the legacy dagger/one-hand-sword rule", () => {
  const expected = fixture<{ ids: number[] }>("left-weapon-list.json").ids;
  const actual = catalog
    .filter(
      (item) =>
        resolveWeaponCapabilities({
          itemTypeId: item.itemTypeId,
          itemSubTypeId: item.itemSubTypeId,
        }).canEquipLeftWeapon,
    )
    .map((item) => item.id);

  assertSameIds(actual, expected, "leftWeapon");
});

test("shield availability matches the legacy AllowShieldTable", () => {
  const expected = fixture<{
    allowsShieldWithoutWeapon: boolean;
    weapons: Array<{ id: number; allowsShield: boolean; allowsAmmo: boolean }>;
  }>("weapon-capabilities.json");

  const mismatched = expected.weapons.filter((entry) => {
    const item = catalogById.get(entry.id);
    if (!item) return false;
    const capabilities = resolveWeaponCapabilities({
      itemTypeId: item.itemTypeId,
      itemSubTypeId: item.itemSubTypeId,
    });
    return capabilities.allowsShield !== entry.allowsShield;
  });

  assert.equal(
    mismatched.length,
    0,
    `allowsShield differs for ${mismatched.length} weapons, e.g. ` +
      mismatched
        .slice(0, 8)
        .map((entry) => `${entry.id} ${catalogById.get(entry.id)?.name ?? "?"}`)
        .join(", "),
  );
});

test("ammo availability and ammo subtype match the legacy mappers", () => {
  const expected = fixture<{
    weapons: Array<{
      id: number;
      allowsAmmo: boolean;
      ammoSubTypeId: number | null;
    }>;
  }>("weapon-capabilities.json");

  const mismatched = expected.weapons.filter((entry) => {
    const item = catalogById.get(entry.id);
    if (!item) return false;
    const capabilities = resolveWeaponCapabilities({
      itemTypeId: item.itemTypeId,
      itemSubTypeId: item.itemSubTypeId,
    });
    return (
      capabilities.allowsAmmo !== entry.allowsAmmo ||
      (capabilities.ammoSubTypeId ?? null) !== entry.ammoSubTypeId
    );
  });

  assert.equal(
    mismatched.length,
    0,
    `ammo capability differs for ${mismatched.length} weapons, e.g. ` +
      mismatched
        .slice(0, 8)
        .map((entry) => `${entry.id} ${catalogById.get(entry.id)?.name ?? "?"}`)
        .join(", "),
  );
});

test("ammo slot contains the legacy ammo items, not consumables", () => {
  const expected = fixture<{ ids: number[] }>("ammo-list.json").ids;
  assertSameIds(catalogIdsForSlot("ammo"), expected, "ammo");
});

test("every equipment slot list matches the legacy dropdown", () => {
  const expected = fixture<{ lists: Record<string, number[]> }>(
    "slot-item-lists.json",
  ).lists;

  // leftWeapon is a capability, not an equipSlots membership, after STEP 1.
  for (const [slot, ids] of Object.entries(expected)) {
    if (slot === "leftWeapon") continue;
    assertSameIds(catalogIdsForSlot(slot as EquipmentSlot), ids, `slot ${slot}`);
  }
});

test("class filtering matches the legacy usableClass/unusableClass rules", () => {
  const expected = fixture<{
    classes: Record<string, { classId: number; usable: number[] }>;
  }>("class-filter.json").classes;

  for (const [className, entry] of Object.entries(expected)) {
    const equipable = catalog.filter((item) =>
      [1, 2, 9, 10].includes(item.itemTypeId),
    );
    const actual = equipable
      .filter((item) => itemMatchesClass(item, entry.classId))
      .map((item) => item.id);

    assert.equal(
      legacyClassToken(entry.classId),
      className,
      `class token for ${entry.classId} should be ${className}`,
    );
    assertSameIds(actual, entry.usable, `class ${className}`);
  }
});

test("accessory refine follows the source flag, not the slot rule", () => {
  // equipment.component.ts:243 consults isRefinable for accessories only; every
  // other slot always offered the 0-18 refine dropdown.
  const expected = fixture<{ refinable: number[] }>("refinable.json");
  const expectedSet = new Set(expected.refinable);

  const accessories = catalog.filter((item) =>
    item.equipSlots.some((slot) => slot === "accLeft" || slot === "accRight"),
  );
  const fabricated = accessories.filter(
    (item) => item.isRefinable && !expectedSet.has(item.id),
  );

  assert.equal(
    fabricated.length,
    0,
    `${fabricated.length} accessories are marked refinable but the legacy source is not, e.g. ` +
      fabricated
        .slice(0, 8)
        .map((item) => `${item.id} ${item.name}`)
        .join(", "),
  );

  const missing = accessories.filter(
    (item) => expectedSet.has(item.id) && !item.isRefinable,
  );
  assert.equal(
    missing.length,
    0,
    `${missing.length} accessories lost the refine flag the source sets`,
  );

  // Weapons and armour keep their refine control.
  const weapon = catalog.find((item) => item.equipSlots.includes("weapon"));
  const armor = catalog.find((item) => item.equipSlots.includes("armor"));
  assert.equal(weapon?.isRefinable, true, "weapons stay refinable");
  assert.equal(armor?.isRefinable, true, "armor stays refinable");
});

test("grade eligibility comes from the source flag, not from refine", () => {
  const gradable = catalog.filter((item) => item.canGrade);
  const sourceFlagged = new Set(
    fixture<{ canGradeIds: number[] }>("gradable.json").canGradeIds,
  );

  const missing = [...sourceFlagged].filter(
    (id) => !gradable.some((item) => item.id === id),
  );
  assert.equal(
    missing.length,
    0,
    `${missing.length} items the source flags canGrade are not gradable`,
  );

  // The remainder are the documented Patent/-LT name heuristics. Pinning the
  // count keeps that over-approximation from drifting silently.
  const heuristicOnly = gradable.filter((item) => !sourceFlagged.has(item.id));
  assert.equal(
    heuristicOnly.length,
    64,
    "the Patent/-LT grade heuristic changed size",
  );
});
